import httpx
from datetime import datetime
from app.core.config import settings

class NotionBot:
    def __init__(self):
        self.headers = {
            "Authorization": f"Bearer {settings.NOTION_TOKEN}",
            "Content-Type": "application/json",
            "Notion-Version": "2022-06-28"
        }
        self.base_url = "https://api.notion.com/v1"

    def _get_risk_label(self, score: int) -> str:
        if score >= 8: return "Critical 🔴"
        if score >= 6: return "High 🟠"
        if score >= 4: return "Medium 🟡"
        return "Low 🟢"

    async def create_incident_report(self, analysis: dict, event_summary: str, pr_url: str):
        """
        Creates a structured Post-Mortem page and returns the page URL.
        """
        risk_score = analysis.get("risk_score", 0)
        
        payload = {
            "parent": {"database_id": settings.NOTION_DATABASE_ID},
            "properties": {
                "Name": {"title": [{"text": {"content": f"NovaScan Alert: {event_summary}"}}]},
                "Risk Level": {"select": {"name": self._get_risk_label(risk_score)}},
                "Risk Score": {"number": risk_score},
                "Status": {"status": {"name": "In Progress"}},
                "Source PR": {"url": pr_url},
                "Detected At": {"date": {"start": datetime.utcnow().isoformat()}}
            },
            "children": [
                {
                    "object": "block",
                    "type": "callout",
                    "callout": {
                        "rich_text": [{"text": {"content": "This report was automatically generated by NovaScan AI. Human intent and code diff correlation completed."}}],
                        "icon": {"emoji": "🤖"},
                        "color": "blue_background"
                    }
                },
                {
                    "object": "block",
                    "type": "heading_2",
                    "heading_2": {"rich_text": [{"text": {"content": "🔍 Intelligence Summary"}}]}
                },
                {
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {"rich_text": [{"text": {"content": analysis.get("reason", "No analysis available.")}}]}
                },
                {
                    "object": "block",
                    "type": "heading_2",
                    "heading_2": {"rich_text": [{"text": {"content": "🛠️ Required Action"}}]}
                },
                {
                    "object": "block",
                    "type": "quote",
                    "quote": {"rich_text": [{"text": {"content": analysis.get("action_needed", "Immediate review required.")}}]}
                }
            ]
        }

        async with httpx.AsyncClient() as client:
            response = await client.post(f"{self.base_url}/pages", headers=self.headers, json=payload)
            if response.status_code != 200:
                print(f"❌ Notion Error: {response.text}")
                return None
            return response.json() # This contains the 'url' field

notion_bot = NotionBot()